# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unikraft < Formula
  desc "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds."
  homepage "https://unikraft.com"
  version "0.6.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.6.1/unikraft-cli_0.6.1_darwin_amd64.tar.gz"
      sha256 "28bf807ffc572b9e2636d6a334fe5370dac6b9329943a3441c43ace8172149ef"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.6.1/unikraft-cli_0.6.1_darwin_arm64.tar.gz"
      sha256 "de824b572f3b069b535c8ab20fc595ff118197e1cfc906a50c4535e361b0717c"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.6.1/unikraft-cli_0.6.1_linux_amd64.tar.gz"
      sha256 "8c8e817305a6fae563ae82e22644af17a22b07447649727880de635deb3583fd"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.6.1/unikraft-cli_0.6.1_linux_arm64.tar.gz"
      sha256 "03ce78181fc99632f538be9d45c3ecfbb6cc5043b757e350073af5646b997b14"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end
end
